### ISSUE TITLE
Non-tiled/un-grouped windows

### ISSUE THREAD

**Issue by kirvedx** [mmod/mmod-panel#10]
User requests the option to separate instances from a group. 

i.e. To show a separate icon for each instance of an application that is currently running.

**Comment by Baltix** [comment]
I think it's better to display thumbnails of all application windows when mouse cursor is over running application icon in the taskbar.
This feature is already implemented in other similar gnome-shell-extensions, see:
https://extensions.gnome.org/extension/265/deepin-enhanced-dock/ 
https://extensions.gnome.org/review/1617

Should I report a separate issue about displayingt humbnails of running apps?

**Comment by kirvedx** [comment]
No this enhancement request is perfect for that addition - thanks!

**Comment by kirvedx** [comment]
Will migrate this to gitlab, or you can if you'd still like to see it implemented [MMOD @ GITLAB](https://gitlab.com/mmod/mmod-panel)
