### ISSUE TITLE
Enable favorites tooltips

### ISSUE THREAD

**Issue by kirvedx** [mmod/mmod-panel#11]
User requests the option to show window-titles (tooltips) on the favorites display.

**Comment by Baltix** [comment]
Please show not only icon in taskbar but also display thumbnails of all windows when mouse cursor is over running application icon in the taskbar.
This feature is already implemented in other similar gnome-shell-extensions, see:
https://extensions.gnome.org/extension/265/deepin-enhanced-dock/ 
https://extensions.gnome.org/review/1617
https://github.com/zpydr/gnome-shell-extension-taskbar

Should I report a separate issue about displayingthumbnails of running apps?

**Comment by kirvedx** [comment]
Well, yes its ok that you put it here too - not a big deal, both dealt with the similar area of the extension

**Comment by kirvedx** [comment]
Will migrate this to Gitlab, or you may as well if you'd stilll like to see it implemented: [MMOD @ GITLAB](https://gitlab.com/mmod/mmod-panel)
