### ISSUE TITLE
Add Repo link to extension Page

### ISSUE THREAD

**Issue by steelbrain** [mmod/mmod-panel#12]
Just like the title says

**Comment by kirvedx** [comment]
I will do that, though there is a repository link in the MMOD-Panel Preferences window's 'About' tab, accessible via the aggregate menu ->MMOD-Panel->Preferences link, or via AI Tweak Tool (select the extension and open preferences via the gear icon)

**Comment by bendem** [comment]
Nobody reads `About` things, but they'll read what's on the page to install the extension.

**Comment by kirvedx** [comment]
Please refer to our new home for further communication regarding this matter:

https://code.mmogp.com/mmod/mmod-panel/issues/8
