### ISSUE TITLE
Don't show duplicate icon for running and favorites

### ISSUE THREAD

**Issue by steelbrain** [mmod/mmod-panel#14]
If an app that is in the favorite list, is running, it is shown twice.

**Comment by kirvedx** [comment]
That's actually not the case.  Some applications have issues and show twice (Chrome and Eclipse are some examples) Though chrome with its last release is actually not doing that.

There are times when a shell bug takes place...which may break the favorites display to do that with chrome and eclipse...but typically a simple shell restart fixes this. It does not happen often with chrome, and I've not experienced it with any other software other than Chrome and Eclipse as I've stated.

I believe the issue you are experiencing is conflict with your many extensions modifying the topbar (which is all MMOD-Panel does).

**Comment by kirvedx** [comment]
If this issue persists for you, please resubmit the issue to [mmod panel at gitlab](https://gitlab.com/mmod/mmod-panel)
