### ISSUE TITLE
extension does not load

### ISSUE THREAD

**Issue by lassizci** [mmod/mmod-panel#18]
I'm on Fedora 20 and GNOME shell 3.10.4 and the extension is installed through extensions.gnome.org and no other extensions installed. Also there are no errors in lg. It works again when I go to preferences and turn it off and on again. ideas?

**Comment by kirvedx** [comment]
Hello,

On Fri, 2015-05-08 at 08:46 -0700, Lassi Pölönen wrote:

> I'm on Fedora 20 and GNOME shell 3.10.4 and the extension is installed
> through extensions.gnome.org and no other extensions installed. Also
> there are no errors in lg. It works again when I go to preferences and
> turn it off and on again. ideas?

Do you have any syslog entries that contain 'Gjs' by chance?

## 

Rik

**Comment by lassizci** [comment]
Found something from syslog. This comes when gnome starts:

(gnome-shell-extension-prefs:31431): Gjs-WARNING **: JS ERROR: Could not load extension mmod-panel: Error: Failed to parse metadata.json: SyntaxError: JSON.parse: bad control character in string literal
createExtensionObject@/usr/share/gnome-shell/js/misc/extensionUtils.js:113
ExtensionFinder<._loadExtension@/usr/share/gnome-shell/js/misc/extensionUtils.js:169
wrapper@/usr/share/gjs-1.0/lang.js:213
@/usr/share/gnome-shell/js/misc/fileUtils.js:50
onNextFileComplete@/usr/share/gnome-shell/js/misc/fileUtils.js:21

when I go to mmod panel preferences and turn it off and on again, the panel moves to bottom as expcted and this is printed:

(gnome-shell:32135): St-CRITICAL *_: st_widget_get_theme_node called on the widget [0x2c95b40 ShellGenericContainer.panel-button clock-display:first-child ("Fri 15 May, 11∶37")] which is not in the stage.
(gnome-shell:32135): St-CRITICAL *_: st_widget_get_theme_node called on the widget [0x2c95b40 ShellGenericContainer.panel-button clock-display:first-child ("Fri 15 May, 11∶37")] which is not in the stage.
(gnome-shell:32135): St-CRITICAL *_: st_widget_get_theme_node called on the widget [0x2c95b40 ShellGenericContainer.panel-button clock-display:first-child ("Fri 15 May, 11∶37")] which is not in the stage.
(gnome-shell:32135): St-CRITICAL *_: st_widget_get_theme_node called on the widget [0x2cbe930 StLabel:last-child first-child ("Fri 15 May, 11∶37")] which is not in the stage.
(gnome-shell:32135): St-CRITICAL *_: st_widget_get_theme_node called on the widget [0x2c95b40 ShellGenericContainer.panel-button clock-display:first-child ("Fri 15 May, 11∶37")] which is not in the stage.
(gnome-shell:32135): St-CRITICAL *_: st_widget_get_theme_node called on the widget [0x2cbe930 StLabel:last-child first-child ("Fri 15 May, 11∶37")] which is not in the stage.
(gnome-shell:32135): St-CRITICAL *_: st_theme_context_get_font: assertion 'ST_IS_THEME_CONTEXT (context)' failed
Window manager warning: Log level 8: pango_font_description_get_size: assertion 'desc != NULL' failed
Window manager warning: Log level 8: pango_font_description_get_size_is_absolute: assertion 'desc != NULL' failed
Window manager warning: Log level 8: pango_font_description_equal: assertion 'desc2 != NULL' failed
Window manager warning: Log level 8: pango_font_description_to_string: assertion 'desc != NULL' failed
(gnome-shell:32135): St-CRITICAL *_: st_widget_get_theme_node called on the widget [0x2c95b40 ShellGenericContainer.panel-button clock-display ("Fri 15 May, 11∶37")] which is not in the stage.
(gnome-shell:32135): St-CRITICAL *_: st_widget_get_theme_node called on the widget [0x2c95b40 ShellGenericContainer.panel-button clock-display ("Fri 15 May, 11∶37")] which is not in the stage.
(gnome-shell:32135): St-CRITICAL *_: st_widget_get_theme_node called on the widget [0x2c95b40 ShellGenericContainer.panel-button clock-display ("Fri 15 May, 11∶37")] which is not in the stage.
(gnome-shell:32135): St-CRITICAL *_: st_widget_get_theme_node called on the widget [0x2cbe930 StLabel:last-child first-child ("Fri 15 May, 11∶37")] which is not in the stage.
(gnome-shell:32135): St-CRITICAL *_: st_widget_get_theme_node called on the widget [0x2c95b40 ShellGenericContainer.panel-button clock-display ("Fri 15 May, 11∶37")] which is not in the stage.
(gnome-shell:32135): St-CRITICAL *_: st_widget_get_theme_node called on the widget [0x2cbe930 StLabel:last-child first-child ("Fri 15 May, 11∶37")] which is not in the stage.
(gnome-shell:32135): St-CRITICAL *_: st_theme_context_get_font: assertion 'ST_IS_THEME_CONTEXT (context)' failed
Window manager warning: Log level 8: pango_font_description_get_size: assertion 'desc != NULL' failed
Window manager warning: Log level 8: pango_font_description_get_size_is_absolute: assertion 'desc != NULL' failed
Window manager warning: Log level 8: pango_font_description_equal: assertion 'desc1 != NULL' failed

**Comment by kirvedx** [comment]
This should be resolved with the later releases.

If you have any further issues, please submit them at [MMOD Panel @ Gitlab](https://gitlab.com/mmod/mmod-panel/issues)

Thanks!
